name: Release Checker
on:
  pull_request_target:
    paths: [ 'version.json' ]
    # Do not allow releases on any other branches
    branches: [ 'release', 'release-*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-check:
    uses: protocol/.github/.github/workflows/release-check.yml@master
    with:
      go-version: 1.20.x
      # Do not require release label for releases on these branches
      branches: release,release-*
